version: '3.8'
services:
  #Container Redis
  redis:
    image: redis:alpine
    container_name: cvreview-redis
    restart: always
    command: redis-server --requirepass redismann
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  #Container PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: cvreview-postgres
    restart: always
    environment:
      POSTGRES_DB: cvreview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresmann
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  redis_data:
  postgres_data: